language: go
sudo: false
dist: trusty
env:
  global:
  - HUGO_BUILD_TAGS="extended"
git:
  depth: false
go:
  - "1.11.5"
  - tip
os:
  - linux
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
  exclude:
  - os: windows
    go: tip

install:
  - go get --tags extended  github.com/spf13/hugo
script:
  - npm install
  - hugo version
  - hugo
  - df -h

before_install:
  - df -h
    # https://travis-ci.community/t/go-cant-find-gcc-with-go1-11-1-on-windows/293/5
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install mingw -y; export PATH=/c/tools/mingw64/bin:"$PATH"; fi
  - gem install asciidoctor
  - type asciidoctor
