language: go
sudo: false
dist: trusty
env:
  global:
  - HUGO_BUILD_TAGS="extended"
git:
  depth: false
go:
  - tip
os:
  - linux

install:
  - go get --tags extended  github.com/spf13/hugo
script:
  - npm install
  - hugo version
  - hugo
before_install:
  - df -h
    # https://travis-ci.community/t/go-cant-find-gcc-with-go1-11-1-on-windows/293/5
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install mingw -y; export PATH=/c/tools/mingw64/bin:"$PATH"; fi
  - gem install asciidoctor
  - type asciidoctor
deploy:
  provider: pages
  skip-cleanup: true
  repo: $GIT_DEPLOY_REPO
  local-dir: $GIT_DEPLOY_DIR
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target-branch: $GIT_DEPLOY_BRANCH
  keep-history: true
  on:
    branch: master
