name: Hugo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    
    - name: install pandoc
      run: |
           wget https://github.com/jgm/pandoc/releases/download/2.10/pandoc-2.10-1-amd64.deb
           sudo dpkg -i pandoc-2.10-1-amd64.deb
 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'
        extended: true
          
    - name: Build
      run: |
       npm install -D --save autoprefixer
       npm install -D --save postcss-cli
       hugo
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        commit_message: 'auto commit [ci skip]'
    - name: Hugo Deploy GitHub Pages
    # You may pin to the exact commit or the version.
    # uses: benmatselby/hugo-deploy-gh-pages@7c17fd574c2d6a3308cc2b0e433e99e9c2e454b5
      uses: benmatselby/hugo-deploy-gh-pages@v1.12.0
      with:
      # The version of hugo to use.
        hugo_version: '0.71.1'
        # If set to `true`, use the *extended* version of hugo.
        hugo_extended: true
        # Your PAT to authorise the action to do things.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # The repo name you want to clone and push to.
        target_repo: wikihub/wikihub.github.io
